### ISSUE TITLE
can't install following your pip instructions

### ISSUE THREAD

**Issue by eiro** [danylo-dubinin/zsh-jupyter-kernel#1]
hello,

i don't know if it's a typo in the doc or if i screwed something but i wasn't enable to run a working kernel using your instructions. the ones described here https://github.com/eiro/play-jupyter/blob/master/Dockerfile are working.

regards,
marc

**Comment by danylo-dubinin** [comment]
Hello, eiro!
Sorry for a very late response, I was on a vacation.

Thank you for fixing the docs, I appreciate it.
I also tested your Dockerfile and it works like a charm.

I linked your repo to the readme file.

**Comment by eiro** [comment]
hello,

> Sorry for a very late response, I was on a vacation.

there was no rush :) hope you enjoyed it.

> Thank you for fixing the docs, I appreciate it.

thank you for doing the job of creating a zsh kernel :) i tried long
time ago but the python part made me run away.

> I also tested your Dockerfile and it works like a charm.

cool! thank you. also thanks to your project, i discovered the zsh
capture by @Valodim so i'm currently experimenting zsh completion for
vim which is very useful for me as i am an intensive user of fc,
zle -N edit-command-line. also inside vim, i use '<,'>term and ! filter.

> I linked your repo to the readme file.

not sure this is a good idea as it really was for testing purposes. Feel
free to add the Dockerfile to your project (i can also make a PR for
that)

regards
marc

**Comment by danylo-dubinin** [comment]
> thank you for doing the job of creating a zsh kernel :) i tried long
time ago but the python part made me run away.

Wow, glad to hear! For me it is important to have a notebook env for shell, but existing Bash kernels are too primitive, except Calysto one, which in its turn seems too overloaded and has complex source code, in my opinion. So here it is, I'm back to improving it now.

> also thanks to your project, i discovered the zsh
capture by @Valodim so i'm currently experimenting zsh completion for
vim which is very useful for me as i am an intensive user of fc,
zle -N edit-command-line. also inside vim, i use '<,'>term and ! filter.

Ha! :) That was a gem for me to discover as well. It's a really impressive 
hackery done there.

Interesting... Never used `fc`. Will give it a try. 

> not sure this is a good idea as it really was for testing purposes. Feel
free to add the Dockerfile to your project (i can also make a PR for
that)

Adding Dockerfile to the project sounds good 👍 
I've piled up all the small things to [../misc](../tree/master/misc), it's a bit of a mess but many links refer to that location, I may reorganize later
